### PR TITLE
Add clear capability to list view controller

### PR DESCRIPTION
**Pull request by nunogoncalves**
Hi,

I use Netfox fairly extensively. This is a shortcut that makes so much sense to me. I'm opening this PR to see if you guys like it (in that case will fix any issues you'd like). Right now the code is duplicated, but if you prefer I can try to "dry" it and any other issue you might want. If you don't like for some reason, let me know to avoid doing anything wrong, but I'll probably start using my fork with this feature. Thank you!

Here's an image displaying the behavour:

<p align="center">

</span>

### CODE REVIEW

**Comment by danielmartinssilva** [comment]
Good job. I would be glad to use this.

**Comment by felipegarciaice** [comment]
Hey @nunogoncalves nice that you manage, but indeed, it's a duplicated code, I just looked in order to proceed with the merge, can you update in order to not have a duplicated code?

It should be the " func clearDataButtonPressedOnTableIndex(_ index: IndexPath)" generic , could be rename the method to " func clearDataButtonPressed(_ index: IndexPath? = nil )", and inside you make the validation, if I have an index do what need and if not go with your implementation.

When finish I will see and if fine we proceed with the pull request! Tnx for helping 💃

**Comment by nunogoncalves** [comment]
Hi @felipeflorencio thanks for your answer. 

I updated the PR, but maybe this is going to require some more discussion. I didn't see a great place to add this to, so I created a protocol in Utils file and added a default implementation for the clear code. 
Let me know your thought, and if you don't like it, where do you think I should put it?

**Comment by felipeflorencio** [comment]
Changed merged, I just waiting for access to publish the pod :D soon I get will be available there, tnx for helping and supporting :D.

**Comment by felipeflorencio** [comment]
@nunogoncalves Done already published 👍

**Comment by nunogoncalves** [comment]
Thank you! That was fast! Considering other OS experiences I had, this was supah fast! :D Thanks again

**Pull request merged**
