### PR TITLE
OSX Support

### PR DESCRIPTION
**Pull request by tbaranes**
It takes a bit more time than expected (not enough free time), but here it is: OS X support! #42 

All the features has been copy from iOS, just missing:
- Sharing by email: not sure if that necessary since the text can be selected / copy
- README update
- Git history improvements (squashed all the commits?)

We test the OS X version in our project these last days , it was working well. So, I think, it would be ok, but maybe iOS needs to be tested again (since, we moved a lot stuff).

From now on, I'm waiting your feedback on:
- Interfaces 
- Code architecture / conception
=> If you want make some change, just ask! 

Hope you will like it :)

screen shot 2016-02-08 at 18 18 38
screen shot 2016-02-08 at 18 18 43
screen shot 2016-02-08 at 18 18 49
screen shot 2016-02-08 at 18 18 55
screen shot 2016-02-08 at 18 18 32
screen shot 2016-02-08 at 18 18 26

### CODE REVIEW

**Comment by kasketis** [comment]
Your work looks awesome guys! :+1:  Thank you so much!!! :beers:  :smiley: 

I tried to test the new library (I just replaced the netfox folder) in a test iOS app that I have and I got the following:

screen shot 2016-02-09 at 9 55 31 am

I think that preprocessor can't exclude OSX xibs when the target is iOS (macros on xibs maybe?). 
Could you please check?

If you want to reproduce it just create an iOS app and paste the following:
<pre>
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.

        NFX.sharedInstance().start()
        loadGetURL("https://www.github.com")
        print("1")
        return true
    }

    func loadGetURL(url : String)
    {
        var req : NSMutableURLRequest
        req = NSMutableURLRequest(URL: NSURL(string: url)!)
        req.HTTPMethod = "GET"

        
        NSURLSession.sharedSession().dataTaskWithRequest(req, completionHandler: {data, response, error in
            print("Response: \(response)")
            if (data != nil) {
                let strData = NSString(data: data!, encoding: NSUTF8StringEncoding)
                print("Body: \(strData)")
            }
            
            
        }).resume()
        
    }
</pre>

**Comment by tbaranes** [comment]
It's exactly that. Xcode will compile all the sources files if you just drag&drop inside. In order to compile on iOS, you will have to remove the OS X files from the iOS target. 
We can create a workaround for the .swift files, but it won't be possible for the xibs.

If added using CocoaPods, you won't have that issue since CocoaPods set the right target directly (I will update the podspec to handle that)

Happy to know you like it :tada:

**Comment by tbaranes** [comment]
I just divide the files in three directories:
- netfox: contains all the common file
   - iOS: contains all the files related to iOS
   - OS X: contains all the files related to OS X

This way, it will be easier to drag&drop directly the right files instead of all.

**Comment by kasketis** [comment]
Thanks mate! I just build it correctly but I see some more issues on controllers

simulator screen shot feb 9 2016 10 45 38 am

e.g
<pre>
    private func showNFXFollowingPlatform()
    {
        var navigationController: UINavigationController?
        
        var listController: NFXListController //-> NFXListController_iOS here
        listController = NFXListController() // -> NFXListController_iOS here

</pre>

Same issue maybe affects and other iOS controllers.

I will make some more regression tests on the following days in order to verify that iOS part is fully functional.
I appreciate your help so far :)

**Comment by tbaranes** [comment]
Uups. That's why I was saying some tests on iOS are necessary 😱 
We didn't test it back at all. Let me know if you want us to fix them or if you prefer take care of them directly (I can add you as a contributor in the fork).

**Comment by kasketis** [comment]
No worries! I will handle them locally. If I need any help I will let you know :) :+1:

**Comment by tbaranes** [comment]
Hi @kasketis! Coming to get some news :)
Sure you don't want any help?

**Comment by kasketis** [comment]
Hi @tbaranes , thanks for your interest!

I have successfully fixed and tested the iOS part but I noticed a strange memory increase during my tests. I think that network manager doesn't release the connection after the request completion (https://github.com/kasketis/netfox/issues/46). 

I want to fix it in order to ship a universal (iOS/OSX) and stable 2.0 version :)

**Comment by tbaranes** [comment]
Good job! :tada: 
This 2.0 sounds really great!

**Comment by tbaranes** [comment]
Until you released the 2.0, do you have any branch that we can target with the last version of Netfox iOS / OS X?

**Comment by kasketis** [comment]
Hi guys,

My apologies for the delayed response! Here you are https://github.com/kasketis/netfox/tree/pr/49  :)

**Comment by tbaranes** [comment]
Hey @kasketis! Just realised we missed something in our OS X implementation: the path where the logs files are stored. Here a potential implementation (in Objective-C) to fix this:


```
- (NSURL *)defaultAppURL {
#if iOS
	// On iOS the Documents directory isn't user-visible, so put files there
	//	NSURL *defaultURL = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] firstObject];
	NSURL *defaultURL = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] firstObject];
#else
	// On OS X it is, so put files in Application Support. If we aren't running
	// in a sandbox, put it in a subdirectory based on the bundle identifier
	// to avoid accidentally sharing files between applications
	NSURL *defaultURL = [[[NSFileManager defaultManager] URLsForDirectory:NSApplicationSupportDirectory inDomains:NSUserDomainMask] firstObject];
	if (![[NSProcessInfo processInfo] environment][@"APP_SANDBOX_CONTAINER_ID"]) {
		NSString *identifier = [[NSBundle mainBundle] bundleIdentifier];
		if ([identifier length] == 0) {
			identifier = [[[NSBundle mainBundle] executablePath] lastPathComponent];
		}
		defaultURL = [defaultURL URLByAppendingPathComponent:identifier isDirectory:YES];
	}
#endif
	return defaultURL;
}
```

**Comment by kasketis** [comment]
Hello guys, :)

This is just an update! Due to lack of free time I was unable to check the memory issues for v2.0. I hope to find some time to solve them and publish the issues and your OSX support soon.

Thanks :+1:

**Comment by tbaranes** [comment]
:beers:

**Comment by tbaranes** [comment]
@kasketis It's been a while now! Still no idea when you will release the 2.0?

**Comment by tbaranes** [comment]
For your information, I created a temporary [public project](https://github.com/tbaranes/kaskentis_netfox) since the podspec of your branch is not compatible with CocoaPods 1.0.
This temporary repot has all the swift warnings fixed, and a podspec up to date for iOS and OSX.

**Comment by tbaranes** [comment]
Closing now 1.8 is released! Thanks :)

**Comment by kasketis** [comment]
Thanks for your support guys! 👍 A thank you section have been added on netfox's main page especially for you ;)

**Comment by kasketis** [comment]
Just a little favor.. is it possible to have a gif with the OSX functionality (like on iOS) in order to replace the static screenshot of the main page?

**Pull request closed without merging**
