### PR TITLE
Fix various Xcode 9 issues not allowing compilation

### PR DESCRIPTION
**Pull request by freak4pc**

### CODE REVIEW

**Comment by Janglinator** [comment]
I'm a tad confused by this.  Are you using the Swift 4 compiler?

**Comment by freak4pc** [comment]
Hey @Janglinator 
This is for Swift 3.2 

First change is moving to correct NSAttribute names. otherwise you got error similar to:
```
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
```

Second change was moving `presentingViewController` to the top. Otherwise compiler complains it is being used before it's being declared.

**Comment by freak4pc** [comment]
@Janglinator I actually just realized `NSAttributedStringKey.foregroundColor` is Swift 4 only (what you have on master right now). Which is why this doesn't build on Swift 3.2 

Did you actually plan on migrating master to Swift 4? Seems a bit too soon, especially since most libraries still haven't migrated. 

If that was the plan we can support both e.g. 

```
#if swift(>=4.0)

#else

#endif
```

**Comment by freak4pc** [comment]
Updated the code

**Comment by freak4pc** [comment]
Should definitely get the README updated if thats the case :) Right now it's talking about Swift 2.

**Comment by Janglinator** [comment]
Lol I never look at the README anymore, I probably should start

**Comment by Janglinator** [comment]
Thank you!

**Pull request merged**
