### PR TITLE
Add support for SPM

### PR DESCRIPTION
**Pull request by gbreen12**
This adds support for Swift Package Manager. Currently only works for iOS and Swift

### CODE REVIEW

**Comment by skydemarcoa** [comment]
Hi @gbreen12, with Carthage we avoided to copy the framework where the configuration was Release.

Do you know how we can achieve the same result with SPM?

**Comment by gbreen12** [comment]
Can you explain a little better what is needed? I'm not sure what you are asking for.

**Comment by gbreen12** [comment]
Oh I think I understand what you are asking. You are saying you don't want to include this framework when you build your iOS app in release mode to make the ipa smaller. Is that right?

**Comment by skydemarcoa** [comment]
I found this solution: https://stackoverflow.com/questions/62837730/swift-package-manager-exclude-from-release

So im ok 👍

**Comment by rae** [comment]
Why hasn't this PR been approved? 👍

**Comment by MaxenceMottard** [comment]
Up

**Comment by jimmya** [comment]
This doesn't seem to work in combination with Alamofire. I guess because https://github.com/kasketis/netfox/blob/92dbe403ab59d4dff96996225042d58475859752/netfox/Core/NFXHelper.swift#L403
Isn't called because `Core/NFXLoader.m` is excluded. 

When using `URLSession.shared` directly it works fine. However when using Alamofire it just doesn't work.

**Comment by bstillitano** [comment]
I recommend using https://github.com/bstillitano/Scyther

It solves this issue and also has a tonne more great features.

See the sample project in the repo for implementation details. In the
meantime I’m writing a proper readme for it.

**Comment by jimmya** [comment]
That's a bit of a shameless plug and totally not related to this PR to be honest.

**Comment by bstillitano** [comment]
I really don’t mind plugging my own libraries. It does exactly what you’re
asking for. Not forcing you to use it. If you don’t want to I can’t hold
you to it.

**Comment by gbreen12** [comment]
I've been using it with Alamofire for a while. I think it just takes an extra step when creating your session:
`
  let config = URLSessionConfiguration.default
  config.protocolClasses?.insert(NFXProtocol.self, at: 0)
  return Session(configuration: config, interceptor: self)
`

**Comment by RobertDresler** [comment]
Any update? I would like to have my project completely without CocoaPods instead of hybrid CocoaPods-SPM project 😅

**Comment by bstillitano** [comment]
> Any update? I would like to have my project completely without CocoaPods instead of hybrid CocoaPods-SPM project 😅

Can I interest you in https://github.com/bstillitano/Scyther

**Comment by kasketis** [comment]
Thank you for your contribution, @gbreen12 ! Closed in favor of https://github.com/kasketis/netfox/pull/216

**Pull request closed without merging**
